import { Project } from '@/types';

export const projects: Project[] = [
    // Shopify Projects
    {
        title: 'Edubily',
        description: 'German-developed dietary supplements with top quality and no fuss. Focused on health and wellness products.',
        technologies: ['Shopify', 'Liquid', 'JavaScript', 'CSS'],
        githubLink: '',
        demoLink: 'https://edubily.de/',
        image: '/projects/edubily.webp',
        featured: true,
        category: 'Shopify',
        role: 'Shopify Developer',
    },
    {
        title: 'Neona Store',
        description: 'Innovative lamps designed to help everyone live a positive, productive, and healthy life. Features minimalist, modern, and sustainable lighting solutions.',
        technologies: ['Shopify', 'Liquid', 'JavaScript', 'CSS'],
        githubLink: '',
        demoLink: 'https://www.neona.store/en',
        image: '/projects/neona_store.webp',
        featured: true,
        category: 'Shopify',
        role: 'Shopify Developer',
    },
    {
        title: 'Von Heesen',
        description: 'High-quality handcrafted leather products including wallets, credit card holders, passport covers, umbrellas, briefcases, travel bags, and backpacks. Reliable business and lifestyle accessories.',
        technologies: ['Shopify', 'Liquid', 'JavaScript', 'CSS'],
        githubLink: '',
        demoLink: 'https://www.von-heesen.com/',
        image: '/projects/von_heesen.webp',
        featured: true,
        category: 'Shopify',
        role: 'Shopify Developer',
    },
    // Web Applications
    {
        title: 'Sneakerlah',
        description: 'Discover curated local fashion brands that blend style and exclusivity.',
        technologies: ['React', 'Redux', 'Bootstrap'],
        githubLink: '',
        demoLink: 'https://sneakerlah.com/',
        image: '/projects/sneakerlah.webp',
        featured: true,
        category: 'Web Apps',
        role: 'Frontend Developer',
    },
    {
        title: 'FlipBizz',
        description: 'Platform for enhancing professional networking.',
        technologies: ['React', 'Redux', 'Bootstrap', 'GraphQL'],
        githubLink: '',
        demoLink: 'https://www.flipbizz.com/',
        image: '/projects/flipbizz.webp',
        featured: true,
        category: 'Web Apps',
        role: 'Frontend Developer',
    },
    {
        title: 'UN Questionnaire',
        description: 'Tool to assess progress towards the Sustainable Development Goals (SDGs).',
        technologies: ['React', 'Redux', 'Bootstrap'],
        githubLink: '',
        demoLink: 'https://assessment.esghub.my/login',
        image: '/projects/un_questionnaire.webp',
        featured: false,
        category: 'Web Apps',
        role: 'Frontend Developer',
    },
    {
        title: 'Adignis',
        description: 'Interactive review platform delivering transparent feedback.',
        technologies: ['React', 'Redux', 'Bootstrap', 'GraphQL', 'PostgreSQL'],
        githubLink: '',
        demoLink: 'https://adignis.com/',
        image: '/projects/adignis.webp',
        featured: false,
        category: 'Web Apps',
        role: 'Full-Stack Developer',
    },
    {
        title: 'AFA Tournament',
        description: 'Platform for organizing and engaging in tournaments.',
        technologies: ['React', 'Redux', 'Bootstrap'],
        githubLink: '',
        demoLink: 'https://tournament.afa-sports.com/',
        image: '/projects/afa_tournament.webp',
        category: 'Web Apps',
        role: 'Frontend Developer',
    },
    {
        title: 'AFA Kiosk',
        description: 'Online court booking platform to promote active lifestyles.',
        technologies: ['React'],
        githubLink: '',
        demoLink: 'https://book.afa-sports.com/',
        image: '/projects/afa_kiosk.webp',
        category: 'Web Apps',
        role: 'Frontend Developer',
    },
    {
        title: 'AFA Coaching',
        description: 'Platform connecting users with seasoned coaches for development.',
        technologies: ['React'],
        githubLink: '',
        demoLink: 'https://staging.coaching-website.afa-sports.com/',
        image: '/projects/afa_coaching.webp',
        category: 'Web Apps',
        role: 'Frontend Developer',
    },
    {
        title: 'Idenfic',
        description: 'Mobile app for verifying online sellers via bank accounts.',
        technologies: ['React'],
        githubLink: '',
        demoLink: 'https://play.google.com/store/apps/details?id=com.onesoftlab.idenfic&hl=en',
        image: '/projects/idenfic.webp',
        featured: false,
        category: 'Web Apps',
        role: 'Frontend Developer',
    },
    {
        title: 'Reskills',
        description: 'Online learning platform with flexible global access.',
        technologies: ['React', 'Vue'],
        githubLink: '',
        demoLink: 'https://www.reskills.com/',
        image: '/projects/reskills.webp',
        category: 'Web Apps',
        role: 'Frontend Developer',
    },
    {
        title: 'TLB',
        description: 'Plastic packaging solutions by TLB Industry Sdn. Bhd.',
        technologies: ['React'],
        githubLink: '',
        demoLink: 'https://www.tlb-group.com/',
        image: '/projects/tlb.webp',
        category: 'Web Apps',
        role: 'Frontend Developer',
    },
    {
        title: 'Pcoins',
        description: 'Malaysian tech company providing hardware & software solutions.',
        technologies: ['React'],
        githubLink: '',
        demoLink: 'https://pineapple.my/',
        image: '/projects/pcoins.webp',
        category: 'Web Apps',
        role: 'Frontend Developer',
    },
    {
        title: 'Rezo',
        description: 'Tech and digital solutions company in Malaysia.',
        technologies: ['React'],
        githubLink: '',
        demoLink: 'https://www.rezo.com.my/',
        image: '/projects/rezo.webp',
        category: 'Web Apps',
        role: 'Frontend Developer',
    },
    {
        title: 'Smart Nurse',
        description: 'MERN stack web application for healthcare services.',
        technologies: ['MongoDB', 'Express', 'React', 'Node.js'],
        githubLink: '',
        demoLink: '',
        image: '/projects/smart nurse.webp',
        featured: false,
        category: 'Web Apps',
        role: 'Full-Stack Developer',
    },
    {
        title: 'Teresa',
        description: 'MERN stack project for managing health services.',
        technologies: ['MongoDB', 'Express', 'React', 'Node.js'],
        githubLink: '',
        demoLink: '',
        image: '/projects/teresa.webp',
        featured: false,
        category: 'Web Apps',
        role: 'Full-Stack Developer',
    },
    {
        title: 'Teresa App',
        description: 'React Native app for medication management.',
        technologies: ['React Native'],
        githubLink: '',
        demoLink: '',
        image: '/projects/teresa.webp',
        featured: false,
        category: 'Web Apps',
        role: 'Mobile Developer',
    },
    // Machine Learning Projects
    {
        title: 'Bangla Digit Recognition',
        description: 'ML model trained on NumtaDB dataset for digit recognition.',
        technologies: ['Python', 'NumPy', 'Pandas', 'Sklearn'],
        githubLink: '',
        demoLink: '',
        image: '/projects/bangla digit.webp',
        category: 'Machine Learning',
        role: 'ML Engineer',
    },
    {
        title: 'Predict Suicidal Thought',
        description: 'ML project to predict suicidal tendencies based on input data.',
        technologies: ['Python', 'Machine Learning'],
        githubLink: '',
        demoLink: '',
        image: '/projects/depression.webp',
        category: 'Machine Learning',
        role: 'ML Engineer',
    },
    {
        title: 'Detect Mask Person',
        description: 'CNN model to detect if a person is wearing a mask.',
        technologies: ['TensorFlow', 'Keras', 'Python'],
        githubLink: '',
        demoLink: '',
        image: '/projects/mask.webp',
        category: 'Machine Learning',
        role: 'ML Engineer',
    },
    // Other Projects
    {
        title: 'Chef Zilla',
        description: 'Restaurant ordering system developed using .NET & C# (MVC).',
        technologies: ['.NET', 'C#', 'MVC'],
        githubLink: '',
        demoLink: '',
        image: '/projects/chef zilla.webp',
        category: 'Other',
        role: 'Full-Stack Developer',
    },
    {
        title: 'Cineplex Management System',
        description: 'Desktop Java Swing application for cineplex operations.',
        technologies: ['Java Swing', 'SQL'],
        githubLink: '',
        demoLink: '',
        image: '/projects/cineplex.webp',
        category: 'Other',
        role: 'Desktop Developer',
    },
    {
        title: 'Coffee House',
        description: 'PHP-based website with HTML, CSS, and Bootstrap for a cafe.',
        technologies: ['HTML', 'CSS', 'Bootstrap', 'PHP'],
        githubLink: '',
        demoLink: '',
        image: '/projects/coffe.webp',
        category: 'Other',
        role: 'Web Developer',
    },
];
